import = ["./theme.toml"]

[font]
size = 9.0

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"

[window.padding]
x = 25
y = 25
